*** Overview
    F4 is Eclipse-based IDE for [[http://fantom.org][Fantom]] programming language, which is written mostly in Fantom using F4 itself.
    
    F4 is based on [[http://www.eclipse.org/downloads/packages/eclipse-classic-372/indigosr2/][Eclipse v3.7.2 Indigo Classic]] with the [[https://eclipse.org/dltk/][Dynamic Languages Toolkit (DLTK) v4.0]].

*** Compiling 
    Currently compiled pods are stored in plug-ins, as F4 can be built only using F4. Therefore, to work on F4 sources use the following workflow:
    - Install latest development snapshot from [[http://download.xored.com/f4/nightly/][F4 Nightly Downloads]]
    - Clone this repository and import all projects
    - Clone [[http://github.com/xored/fantom-runtime][Fantom Runtime]] and import all projects

    Now you can modify the F4 source code and launch a new runtime version by running =com.xored.f4.product= as an eclipse application.

*** Packaging
    Maven is used to package F4. [[http://archive.apache.org/dist/maven/maven-3/3.2.1/binaries/][Maven 3.2.1]] is known to work.

    Run =mvn clean package= in project root to build F4 as standalone product. An eclipse update site will be assembled the =repository/target/repository= folder, and full installation products under =product/target/products/=.

**** Testing
    Run =mvn clean verify= in project root to F4 and run [[http://rcptt.xored.com][RCPTT]] tests.
