*** Overview
    F4 is Eclipse-based IDE for [[http://fantom.org][Fantom]] programming language, which is written mostly on Fantom using F4 itself.

*** Compiling 
    Currently we store compiled pods right in plug-ins, as F4 can be built only using F4. Therefore, to work on F4 sources use the following workflow:
    - Install latest development snapshot from [[http://build.xored.com/browse/F4-F4NTLY/latest/artifact/shared/repository][this update site]] into [[http://www.eclipse.org/downloads/packages/eclipse-classic-372/indigosr2/][Eclipse Indigo Classic]].
    - Clone this repository and import all projects
    - Clone [[http://github.com/xored/fantom-runtime][Fantom Runtime]] and import all projects

    Now you can modify its sources and launch runtime version of F4 to check whether it works as expected.

*** Packaging
    - Run =mvn clean package= in project root to build update site containing F4 features and run [[http://www.xored.com/products/q7][Q7]] tests. Update site will be assembled into =repository/target/repository= folder.
    - Once update site is built, execute =mvn clean package -f pom-product.xml= to build F4 as standalone product (under =product/target/products/=).
